
#elasticsearch 配置
#数据源配置
spring:
  datasource:                                   #数据源相关配置
    type: com.zaxxer.hikari.HikariDataSource    #hikari
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodie-shop?characterEncoding=UTF-8&useSSL=false&useUnicode=true&serverTimezone=UTC
    username: root
    password: root

  data:
    elasticsearch:
      cluster-name: my-es
      cluster-nodes: 10.0.0.241:9300 #java端口: 9300， restful:9200




#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8033